CLI added
bragov4ik/go-kys pull request #2
Opened 2021-09-26 13:55 UTC by Feyd-Rauth

2021-09-26 14:53 UTC, i1i1 requested changes

2021-09-26 14:53 UTC, i1i1 commented on cmd/gokys/main.go
>  	_ "github.com/bragov4ik/go-kys/pkg/kys"
Можешь убрать отсюда `_`. Будет легче читать исходники

2021-09-26 14:53 UTC, i1i1 commented on README.md
> +$ ./gokys -d . # calculates for project
Можно узнать с помощью stat-а, является ли путь директорией или файлом. Поэтому по моему не нужны отдельные флаги для этого.

2021-09-26 14:53 UTC, i1i1 commented on README.md
> +$ ./gokys -f "a.go b.go c.go" # calculates for multiple files
Закавычивать это плохо. В unix системах название файла это любая последовательность байтов в которой нет нулевого байта.

2021-09-26 14:53 UTC, i1i1 commented on cmd/gokys/main.go
> +		}
можно тут рекурсивно запуститься кстати. В теории потом еще и распараллелить можно будет

2021-09-26 14:58 UTC, Feyd-Rauth commented on README.md
> +$ ./gokys -d . # calculates for project
А как собственно аргументы без флагов парсить? Я находил только через flag

2021-09-26 20:40 UTC, Feyd-Rauth commented on cmd/gokys/main.go
> +		}
Оно же и так рекурсивно проходится не? Я просто еще не понимаю как нормально можно здесь в рекурсию уйти

2021-09-27 09:01 UTC, i1i1 commented on cmd/gokys/main.go
> +		}
Walk ходит прям по всем директориям рекурсивно? Если так, то ок. Просто наверное он итерирует по файлам и директориям внутри этой директории только (в глубь не идёт)

2021-09-27 09:02 UTC, Feyd-Rauth commented on cmd/gokys/main.go
> +		}
Он идет вглубь

2021-09-27 09:06 UTC, i1i1 approved these changes

2021-09-27 09:07 UTC, merged